---
hero_image: images/rainbow-predictor.png
theme: red
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Regenboog Voorspeller
description: Toon een regenboog wanneer aan de voorwaarden is voldaan.
original_url: https://codeclubprojects.org/en-GB/sense-hat/rainbow-predictor
interests: weather
technologies: sense-hat
site_areas: projects
hardware: sense-hat
software: ''
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: 'Inleiding: '
  - 
    title: Een regenboog tekenen
  - 
    title: Uitlezen van de sensorgegevens
  - 
    title: Een regenboog voorspellen
  - 
    title: 'Uitdaging: meer weer'
