---
hero_image: images/banner.png
theme: red
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Rainbow Predictor
description: Display a rainbow when the conditions are met.
original_url: https://codeclubprojects.org/en-GB/sense-hat/rainbow-predictor
interests: outdoors
technologies: sense-hat
site_areas: projects
hardware: sense-hat
software: ''
version: 3
last_tested: 2017-01-01
steps: 
- title: 'Introduction: '
- title: Drawing a rainbow
- title: Reading the sensor data
- title: Predicting a rainbow
- title: 'Challenge: More Weather'