---
hero_image: images/rainbow-predictor.png
theme: red
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Pronosticador de arco iris
description: Muestra un arcoíris cuando se cumplan las condiciones.
original_url: https://codeclubprojects.org/en-GB/sense-hat/rainbow-predictor
interests: wheather
technologies: sense-hat
site_areas: projects
hardware: sense-hat
software: ''
version: 3
last_tested: 2017-01-01
steps:
- title: Introducción
  completion: engaged
- title: Dibujando un arco iris
- title: Leyendo los datos del sensor
- title: Prediciendo un arco iris
  completion: internal
- title: 'Reto: Más climas'
