---
hero_image: images/rainbow-predictor.png
theme: red
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Previsor de Arco-íris
description: Exibir um arco-íris quando as condições são atingidas.
original_url: https://codeclubprojects.org/en-GB/sense-hat/rainbow-predictor
interests: weather
technologies: sense-hat
site_areas: projects
hardware: sense-hat
software: ''
version: 3
last_tested: 01/01/2017
steps:
- title: Introdução
  completion: engaged
- title: Desenhando um arco-íris
- title: Lendo os dados do sensor
- title: Prevendo um arco-íris
  completion: internal
- title: 'Desafio: Mais Clima'
