---
hero_image: images/rainbow-predictor.png
theme: red
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Predictor de l'arc de Sant Martí
description: Mostra un arc de Sant Martí quan es compleixen les condicions.
original_url: https://codeclubprojects.org/en-GB/sense-hat/rainbow-predictor
interests: weather
technologies: sense-hat
site_areas: projects
hardware: sense-hat
software: ''
version: 3
last_tested: 2017-01-01
steps:
- title: Introducció
  completion: engaged
- title: Dibuixant un arc de Sant Martí
- title: Llegint les dades del sensor
- title: Predient un arc de Sant Martí
  completion: internal
- title: 'Repte: Més Temps'
