---
hero_image: images/rainbow-predictor.png
theme: red
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-2, phys-comp-0, manufacture-0, community-0
title: Rainbow Predictor
description: Display a rainbow when the conditions are met.
original_url: https://codeclubprojects.org/en-GB/sense-hat/rainbow-predictor
interests: מזג אוויר
technologies: sense-hat
site_areas: פרויקטים
hardware: sense-hat
software: ''
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: 'מבוא: '
  - 
    title: Drawing a rainbow
  - 
    title: Reading the sensor data
  - 
    title: Predicting a rainbow
  - 
    title: 'Challenge: More Weather'
