---
hero_image: images/rainbow-predictor.png
theme: 빨간
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, 디자인 -0, 프로그래밍 -1, phys-comp-0, 제조 -0, 커뮤니티 -0
title: Rainbow Predictor
description: Display a rainbow when the conditions are met.
original_url: https://codeclubprojects.org/en-GB/sense-hat/rainbow-predictor
interests: 날씨
technologies: sense-hat
site_areas: projects
hardware: sense-hat
software: ''
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: '들어가며: '
  - 
    title: Drawing a rainbow
  - 
    title: Reading the sensor data
  - 
    title: Predicting a rainbow
  - 
    title: 'Challenge: More Weather'
