---
hero_image: images/rainbow-predictor.png
theme: red
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Prognoza tęczy
description: Wyświetl tęczę, gdy zostaną spełnione warunki.
original_url: https://codeclubprojects.org/en-GB/sense-hat/rainbow-predictor
interests: pogoda
technologies: sense-hat
site_areas: projekty
hardware: sense-hat
software: ''
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: 'Wprowadzenie: '
  - 
    title: Rysowanie tęczy
  - 
    title: Odczytywanie danych z czujnika
    completion:
      - engaged
  - 
    title: Przewidywanie tęczy
    completion:
      - internal
  - 
    title: 'Wyzwanie: Więcej pogody'
