---
hero_image: images/rainbow-predictor.png
theme: red
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Prédicteur d'arc-en-ciel
description: Afficher un arc-en-ciel lorsque les conditions sont remplies.
original_url: https://codeclubprojects.org/en-GB/sense-hat/rainbow-predictor
interests: weather
technologies: sense-hat
site_areas: projects
hardware: sense-hat
software: ''
version: 3
last_tested: 2017-01-01
steps:
- title: Introduction
- title: Dessiner un arc-en-ciel
- title: Lecture des données du capteur
  completion:
  - engaged
- title: Prédire un arc-en-ciel
  completion:
  - internal
- title: 'Défi : Plus de Météo'
