---
hero_image: images/rainbow-predictor.png
theme: red
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programmation-1, phys-comp-0, fabrication-0, communauté-0
title: Rainbow Predictor
description: Display a rainbow when the conditions are met.
original_url: https://codeclubprojects.org/en-GB/sense-hat/rainbow-predictor
interests: météo
technologies: sense-hat
site_areas: projets
hardware: sense-hat
software: ''
version: 3
last_tested: 01/01/2017
steps:
  - 
    title: 'Introduction'
  - 
    title: Drawing a rainbow
  - 
    title: Reading the sensor data
  - 
    title: Predicting a rainbow
  - 
    title: 'Challenge: More Weather'
