---
hero_image: images/rainbow-predictor.png
theme: red
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Predittore di arcobaleno
description: Mostra un arcobaleno quando le condizioni sono soddisfatte.
original_url: https://codeclubprojects.org/en-GB/sense-hat/rainbow-predictor
interests: weather
technologies: sense-hat
site_areas: projects
hardware: sense-hat
software: ''
version: 3
last_tested: 2017-01-01
steps:
- title: Introduzione
- title: Disegnare un arcobaleno
- title: Leggere i dati dai sensori
  completion:
  - engaged
- title: Prevedere un arcobaleno
  completion:
  - internal
- title: 'Sfida: più condizioni meteo'
