---
hero_image: images / rainbow-predictor.png
theme: red
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, tasarım-0, programlama-1, phys-comp-0, üretim-0, topluluk-0
title: Gökkuşağı Tahmincisi
description: Uygun koşullar gerçekleştiğinde gökkuşağının görüntülenmesi.
original_url: https://codeclubprojects.org/en-GB/sense-hat/rainbow-predictor
interests: hava Durumu
technologies: sense-hat
site_areas: projects
hardware: sense-hat
software: ''
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: 'Giriş: '
  - 
    title: Gökkuşağının çizilmesi
  - 
    title: Sensör verilerinin okunması
  - 
    title: Gökkuşağının tahmin edilmesi
  - 
    title: 'Meydan Okuma: Daha fazla hava durumu'
